notes = {
    "do": 60,
    "do_d": 61,
    "re": 62,
    "re_d": 62 + 1,
    "mi": 64,
    "fa": 65,
    "fa_d": 65 + 1,
    "sol": 67,
    "sol_d": 67 + 1,
    "la": 69,
    "la_d": 69 + 1,
    "si": 71,
}

octave = 12

gammes = {
    "do_majeur": [
        notes["do"],
        notes["re"],
        notes["mi"],
        notes["fa"],
        notes["sol"],
        notes["la"],
        notes["si"],
        notes["do"] + octave
    ],
    "la_mineur": [
        notes["la"] - octave,
        notes["si"] - octave,
        notes["do"],
        notes["re"],
        notes["mi"],
        notes["fa"],
        notes["sol_d"],
        notes["la"]
    ],
    "re_majeur": [
        notes["re"],
        notes["mi"],
        notes["fa_d"],
        notes["sol"],
        notes["la"],
        notes["si"],
        notes["do_d"] + octave,
        notes["re"] + octave,
    ],
    "si_mineur": [
        notes["si"] - octave,
        notes["do_d"],
        notes["re"],
        notes["mi"],
        notes["fa_d"],
        notes["sol"],
        notes["la_d"],
        notes["si"],
    ],
    "mi_bemol_majeur": [
        notes["re_d"],
        notes["fa"],
        notes["sol"],
        notes["sol_d"],
        notes["la_d"],
        notes["do"] + octave,
        notes["re"] + octave,
        notes["re_d"] + octave,
    ],
    "do_mineur": [
        notes["do"],
        notes["re"],
        notes["re_d"],
        notes["fa"],
        notes["sol"],
        notes["la_d"],
        notes["si"],
        notes["do"] + octave,
    ],
    "fa_majeur": [
        notes["fa"] - octave,
        notes["sol"] - octave,
        notes["la"] - octave,
        notes["la_d"] - octave,
        notes["do"],
        notes["re"],
        notes["mi"],
        notes["fa"],
    ],
    "re_mineur": [
        notes["fa"] - octave,
        notes["sol"] - octave,
        notes["la"] - octave,
        notes["la_d"] - octave,
        notes["do"],
        notes["re"],
        notes["mi"],
        notes["fa"],
    ],
}
